### ISSUE TITLE
笑死我了原来是国内公司啊， 这么搞是不是要骗科研费, 跟 cec ide一个样是吗笑死了

### ISSUE THREAD

**Issue by RTAkland** [deepseek-ai/DeepSeek-V3#150]

**Comment by RTAkland** [comment]
你网站山给出的数据碾压4o真的要笑死人

**Comment by Xuanwo** [comment]
生动诠释了什么叫半瓶子水晃荡

**Comment by RTAkland** [comment]
哥别骂我了我错了我不该抨击国产的别骂我了别开哟😭

**Comment by XXXXRT666** [comment]
什么杀软

**Comment by RTAkland** [comment]
> 什么杀软
> ![image](https://github.com/user-attachments/assets/5dc3fb05-64aa-42de-844c-c5da22a40623)

这就是你没素质了

**Comment by Xuanwo** [comment]
问题不在于 “抨击国产”，而且不加了解和分析的直接给项目扣帽子。开源社区欢迎热情的年轻人，希望下一次相遇不是在 Spam Issue 里。

**Comment by RTAkland** [comment]
> 问题不在于 “抨击国产”，而且不加了解和分析的直接给项目扣帽子。开源社区欢迎热情的年轻人，希望下一次相遇不是在 Spam Issue 里。

我真的知道错了别骂我了我下次真的不这样了😭，我当初就是因为觉得14次提交有1w star不真实我在查看了仓库的star趋势和查看了issus才到某科研基地群内发表了一些言论

**Comment by XXXXRT666** [comment]
私下发表就算了，还把他发在官方issue底下，这不是明摆着找骂吗？注意公开言论

**Comment by RTAkland** [comment]
> 私下发表就算了，还把他发在官方issue底下，这不是明摆着找骂吗？希望你下次注意公开言论

是这样的但是你骂人就是你没素质了

**Comment by djkcyl** [comment]
![442bb2409e5d9c495ccb8de2954df942](https://github.com/user-attachments/assets/c6afe854-c210-4516-85ae-6547b9499b34)

**Comment by TimeBather** [comment]
~~不就是做个xx吗为什么这么多star？没说关就一定是开了.jpg~~

**Comment by KakaruHayate** [comment]
> > 什么杀软
> > ![image](https://private-user-images.githubusercontent.com/157766680/399438859-5dc3fb05-64aa-42de-844c-c5da22a40623.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzY1NjQsIm5iZiI6MTczNTYzNjI2NCwicGF0aCI6Ii8xNTc3NjY2ODAvMzk5NDM4ODU5LTVkYzNmYjA1LTY0YWEtNDJkZS04NDRjLWM1ZGEyMmE0MDYyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQwOTExMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmU5OGY2YWQxNjcwM2E1Mjc1YjQwZTM0OTlhYmIwZjFjNTgxZGYyNjc5YzIwOTE4MzYxN2VkYWE0MThiYWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3i-9ugADQNbDe3oQMB-ELfci9talZIfrfpqOeUoi1Rk)
> 
> 这就是你没素质了

🤣这下高素质劣势了

**Comment by RTAkland** [comment]
你也是哈😊

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: KakaruHayate ***@***.***>
发送时间: Tuesday, December 31, 2024 5:16:03 PM
收件人: deepseek-ai/DeepSeek-V3 ***@***.***>
抄送: RTAkland ***@***.***>; Author ***@***.***>
主题: Re: [deepseek-ai/DeepSeek-V3] 1 (Issue #150)


什么杀软
[image]<https://private-user-images.githubusercontent.com/157766680/399438859-5dc3fb05-64aa-42de-844c-c5da22a40623.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzY1NjQsIm5iZiI6MTczNTYzNjI2NCwicGF0aCI6Ii8xNTc3NjY2ODAvMzk5NDM4ODU5LTVkYzNmYjA1LTY0YWEtNDJkZS04NDRjLWM1ZGEyMmE0MDYyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQwOTExMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmU5OGY2YWQxNjcwM2E1Mjc1YjQwZTM0OTlhYmIwZjFjNTgxZGYyNjc5YzIwOTE4MzYxN2VkYWE0MThiYWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3i-9ugADQNbDe3oQMB-ELfci9talZIfrfpqOeUoi1Rk>

这就是你没素质了

🤣这下高素质劣势了

**Comment by JasonWues** [comment]
招笑

**Comment by Haerbin23456** [comment]
慕名而来

**Comment by bennylii** [comment]
慕名而来，楼主顶着这个头像还以为是反串

**Comment by AluminiumOxide** [comment]
ᕕ(◠ڼ◠)ᕗ
病非全力

**Comment by int-9e583** [comment]
前来吃瓜
