### ISSUE TITLE
Request for Dockerfile or Prebuilt Docker Container

### ISSUE THREAD

**Issue by Emilio942** [deepseek-ai/DeepSeek-V3#26]
Hi,

I’m using the `DeepSeek-V3-Base` model and have set up everything manually so far. However, it would be much more convenient if there were an official Dockerfile or prebuilt Docker container available for easier integration.

Does an official Docker setup for this model exist? If not, would it be possible to provide one?  
A prebuilt container bundling the model and its dependencies would greatly simplify the deployment process for users.

Thank you in advance for your help!  
Looking forward to your response.

Best regards,  
Emilio Frittrang

Are there any specific optimizations or configurations required to efficiently run the DeepSeek-V3-Base model in a Docker environment?

# Base image
FROM python:3.10-slim

# Install git and clean up temporary files
RUN apt-get update && apt-get install -y git && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Clone the repository and install dependencies
RUN git clone https://github.com/deepseek-ai/DeepSeek-V3.git . && \
    pip install --no-cache-dir -r inference/requirements.txt

# Default command to run the model
CMD ["python", "inference/generate.py"]

**Comment by GeeeekExplorer** [comment]
Actually the infer demo is slow but the compatibility is good because we built the demo entirely using pytorch and triton code. No special configuration is required.

**Comment by mowentian** [comment]
For actual deployment, you can use the Docker files provided by sglang, lmdeploy, or vllm, among others. The community support for us is also quite robust.

**Comment by Emilio942** [comment]
thank you.
