### ISSUE TITLE
[Question] On NVLink bandwidth of H800

### ISSUE THREAD

**Issue by GHGmc2** [deepseek-ai/DeepSeek-V3#28]
> NVLink offers a bandwidth of 160 GB/s, roughly 3.2 times that of IB (50 GB/s).

May I know why the bandwidth of NVLink on H800 is 160GB/s, instead of 400GB/s?

Thanks.

**Comment by shenkele2016** [comment]
same question

**Comment by mowentian** [comment]
400GB/s 是双向理论值，160GB/s 是我们的单向实测

**Comment by GHGmc2** [comment]
> 400GB/s 是双向理论值，160GB/s 是我们的单向实测

谢谢。那IB带宽50GB/s也是单向实测值吗？

**Comment by yiakwy-xpu-ml-framework-team** [comment]
> 400GB/s 是双向理论值，160GB/s 是我们的单向实测

Could I get the nccl test snapshot (both algorithm bandwidth) of all to all test with multiple nodes ?

**Comment by shenh10** [comment]
> > 400GB/s 是双向理论值，160GB/s 是我们的单向实测
> 
> 谢谢。那IB带宽50GB/s也是单向实测值吗？

同问。IB connect X-7 400Gb/s 像是用的理论值。 @mowentian

**Comment by renwuli** [comment]
> 400GB/s 是双向理论值，160GB/s 是我们的单向实测

可以分享一下您的单向实测脚本吗？
