### ISSUE TITLE
模型文件可否选择性下载

### ISSUE THREAD

**Issue by cpken** [deepseek-ai/DeepSeek-V3#29]
准备想部署体验，看到 [HuggingFace](https://huggingface.co/deepseek-ai/DeepSeek-V3) 上有很多的模型文件提供下载，请问是否可选择单一的模型文件下载，还是全部需要下载下来呢？

**Comment by AiharaMahiru** [comment]
> 准备想部署体验，看到 [HuggingFace](https://huggingface.co/deepseek-ai/DeepSeek-V3) 上有很多的模型文件提供下载，请问是否可选择单一的模型文件下载，还是全部需要下载下来呢？

模型大小1300gb+，都要下载吧

**Comment by cnsky2016** [comment]
全部下载才能运行
